module TyRE.Extra.Elab

import Language.Reflection
import Data.String
import Data.Maybe

public export
isModPart : String -> Bool
isModPart x = case unpack x of
    [] => False
    c :: cs => isUpper c && all isAlpha cs

public export
unAsModPart : UserName -> Maybe String
unAsModPart (Basic n) = if isModPart n then Just n else Nothing
unAsModPart _ = Nothing

public export
nsAsModParts : Namespace -> List String
nsAsModParts (MkNS ns) = ns

public export
nameAsMod : Name -> Maybe ModuleIdent
nameAsMod (UN n) = Just (MkMI [!(unAsModPart n)])
nameAsMod (NS ns (UN n)) = Just (MkMI (!(unAsModPart n) :: nsAsModParts ns))
nameAsMod _ = Nothing

export
modAsNamespace : ModuleIdent -> Namespace
modAsNamespace (MkMI parts) = MkNS parts

export
ttimpList : List TTImp -> TTImp
ttimpList [] = `(Nil)
ttimpList (x :: xs) = `(~x :: ~(ttimpList xs))

export
ttimpMaybe : Maybe TTImp -> TTImp
ttimpMaybe (Just x) = `(Just ~x)
ttimpMaybe Nothing = `(Nothing)

mapVar : (Name -> Name) -> TTImp -> TTImp
mapVar upd = mapTTImp $ \case
    IVar fc n => IVar fc (upd n)
    t => t

export
replaceNs : (old, new : Namespace) -> TTImp -> TTImp
replaceNs old new = mapVar $ \case
    NS ns n => if ns == old then NS new n else NS ns n
    n => n

parameters (source : Name) (target : Name)
    public export
    replaceHead : TTImp -> TTImp
    replaceHead t@(IVar fc n) = if n == source then IVar fc target else t
    replaceHead (IApp fc f x) = IApp fc (replaceHead f) x
    replaceHead t = t

    public export
    replaceClause : Clause -> Clause
    replaceClause (PatClause fc lhs rhs) = PatClause fc (replaceHead lhs) rhs
    replaceClause c = c

    public export
    replaceNameDecl : Decl -> Decl
    replaceNameDecl
        d@(IClaim
            (MkFCVal fc1
                (MkIClaimData rig vis opts
                    (MkTy fc2 (MkFCVal fc3 n) ty))))
        = if n == source
            then IClaim (MkFCVal fc1 (MkIClaimData rig vis opts (MkTy fc2 (MkFCVal fc3 target) ty)))
            else d
    replaceNameDecl d@(IDef fc n cs) = if n == source
        then IDef fc target (map replaceClause cs)
        else d
    replaceNameDecl d = d

export
writeIfChanged : (projName : String) -> LookupDir -> (fname : String) -> (content : String) -> Elab ()
writeIfChanged projName dir fname content = do
    let genComment = "-- @generated by \{projName}"
    let content' = genComment ++ "\n" ++ content
    changed <- case !(readFile dir fname) of
            Just old => do
                let (l1 :: _) = lines old
                    | _ => fail "\{fname} is not a generated file. Refusing to overwrite"
                when (l1 /= genComment)
                    $ fail "\{fname} is not a generated file. Refusing to overwrite"
                pure $ content /= old
            Nothing => pure True
    when changed $ writeFile dir fname content'


export
contains : Eq a => List a -> a -> Bool
contains [] _ = False
contains (x :: xs) y = x == y || (xs `contains` y)

export
modIdentAsPath : ModuleIdent -> String
modIdentAsPath (MkMI parts) = showSep "/" (reverse parts) ++ ".idr"

export
changeVis : (Maybe TTImp -> Visibility) -> Decl -> Decl
changeVis vis (IClaim (MkFCVal fc (MkIClaimData rig _ opts type@(MkTy _ _ ty))))
    = IClaim (MkFCVal fc (MkIClaimData rig (vis (Just ty)) opts type))
changeVis vis (IData fc _ mtreq dt) = IData fc (SpecifiedValue $ vis Nothing) mtreq dt
changeVis vis (IParameters fc params decls) = IParameters fc params (map (changeVis vis) decls)
changeVis vis (IRecord fc mstr _ mtreq rec) = IRecord fc mstr (SpecifiedValue $ vis Nothing) mtreq rec
changeVis vis (INamespace fc ns decls) = INamespace fc ns (map (changeVis vis) decls)
changeVis vis d = d

namespace ModuleIdent
    public export
    fromName : (n : Name) -> {auto 0 isJust : IsJust (nameAsMod n)} -> ModuleIdent
    fromName n = fromJust @{isJust} $ nameAsMod n

export
currentNS : Elab Namespace
currentNS = do
    NS ns _ <- inCurrentNS (UN (Basic "foo"))
        | _ => fail "Could not find current namespace"
    pure ns

export
(++) : Namespace -> Namespace -> Namespace
MkNS xs ++ MkNS ys = MkNS (ys ++ xs)
